// vuejs/js/components/Employer.vue
<template>
	<div class='employer' itemprop='employee' itemscope itemtype='http://schema.org/EmployeeRole'>
		<div class='jobDates'>
			<span class='jobStart' itemprop='startDate' :data-actualdate='this.itemdata.start_date'>
			{{this.itemdata.start_date  | formatDate}}
			</span><span class='jobEnd' itemprop='endDate' :data-actualdate='this.itemdata.end_date'>
				{{endDate}}
			</span>
		</div>
		<div class='jobPosition' itemprop='roleName'>{{this.itemdata.position}}</div>
		<div class='jobEmployer' itemprop='name' itemscope itemtype='http://schema.org/Organization'>{{this.itemdata.title.rendered}}</div>
		<div class='jobAddress' itemprop='address' itemscope itemtype='http://schema.org/Organization'>{{this.itemdata.location}}</div>
		<div class='jobDescription' itemprop='description' v-html='this.itemdata.content.rendered'></div>
		<div class='jobAddl' itemprop='alternateName' v-if='this.itemdata.additional'>ADDITIONAL: {{this.itemdata.additional}}</div>
	</div>
</template>

<script>
export default {
	name: 'employer',
	data() {
		return {};
	},
	props: ['itemdata'],
	computed: {
		endDate: function () {
			return this.itemdata.still_employed === '1' ? 'Present' :  Vue.options.filters.formatDate(this.itemdata.end_date);
		}
	}
}
</script>

<style></style>

// react/src/components/resume/Employer.tsx
import * as React from 'react';
import { formatDate } from 'utilities';

export interface IEmployerProps {
	title: string; // title.rendered
	location: string;
	position: string;
	startDate: string; // start_date
	additional: string;
	endDate: string; // end_date
	stillEmployed: boolean;
}

const getDate = (dataStr: string, present?: boolean): string => {
	return present ? 'Present' : formatDate(dataStr) || '';
};

export class Employer extends React.Component<IEmployerProps, any> {
	public render() {
		return (
			<div className="employer" itemProp="employee" itemScope={true} itemType="http://schema.org/EmployeeRole">
				<div className="jobDates">
					<span className="jobStart" itemProp="startDate" data-actualdate="this.props.startDate">
						{getDate(this.props.startDate)}
					</span>
					<span className="jobEnd" itemProp="endDate" data-actualdate="this.props.endDate">
						{getDate(this.props.endDate, this.props.stillEmployed)}
					</span>
				</div>
				<div className="jobPosition" itemProp="roleName">
					{this.props.position}
				</div>
				<div className="jobEmployer" itemProp="name" itemScope={true} itemType="http://schema.org/Organization">
					{this.props.title}
				</div>
				<div
					className="jobAddress"
					itemProp="address"
					itemScope={true}
					itemType="http://schema.org/Organization"
				>
					{this.props.location}
				</div>
				<div className="jobDescription" itemProp="description" />
				{/* {this.props.content.rendered} */}
				{this.props.additional.length && (
					<div className="jobAddl" itemProp="alternateName">
						ADDITIONAL: {this.props.additional}
					</div>
				)}
			</div>
		);
	}
}
