// vuejs/js/components/Reference.vue
<template>
	<div class="reference" itemprop="review" itemscope itemtype="http://schema.org/CreativeWork">
		<div class='refDetails' v-html="this.itemdata.content.rendered" itemprop="reviewBody"></div>
		<div class='refAuthor' itemprop="author">{{this.itemdata.title.rendered}}</div>
		<div class='refTitle' itemprop="reviewAspect">{{this.itemdata.job_title}}</div>
		<div class='refDate' itemprop="dateCreated" data-actualdate='this.itemdata.date_provided'>{{this.itemdata.date_provided  | humanizeDate }}</div>
	</div>
</template>

<script>
export default {
	name: 'reference',
	data() {
		return {};
	},
	props: ['itemdata']
};
</script>

<style></style>

// react/src/components/resume/Reference.tsx
import * as React from 'react';

export interface IReferenceProps {
	temp?: string;
}

export class Reference extends React.Component<IReferenceProps, any> {
	public render() {
		return (
			<div className="reference" itemProp="review" itemScope={true} itemType="http://schema.org/CreativeWork">
				{/* <div className="refDetails" itemProp="reviewBody">
					{this.props.content.rendered}
				</div>
				<div className="refAuthor" itemProp="author">
					{this.props.title.rendered}
				</div>
				<div className="refTitle" itemProp="reviewAspect">
					{this.props.job_title}
				</div>
				<div className="refDate" itemProp="dateCreated" data-actualdate="this.props.date_provided">
					{this.props.date_provided | humanizeDate}
				</div> */}
			</div>
		);
	}
}
