// react/src/components/resume/Education.tsx
import * as React from 'react';

export interface IEducationProps {
	temp?: string;
}

export class Education extends React.Component<IEducationProps, any> {
	public render() {
		return (
			<div>
				{/* <div className='education' itemScope={true} itemType='http://schema.org/CourseInstance' className=''eduType-'+this.props.course_type'>
		<div className='eduDate' itemProp='endDate' data-actualdate='this.props.completion'>{this.props.completion | formatDate('true') }</div>
		<div className='eduEvent' itemProp='subEvent'>{this.props.title.rendered}</div>
		<div className='eduProvider' itemProp='organizer'>
			<a :href='this.props.location' target='_blank' rel='noopener noreferrer'>{{this.props.provider}}</a>
			<span className='eduAward' itemProp='award' v-if='this.props.award'> - {{this.props.award}}</span>
		</div>
		<div className='eduDescription' itemProp='about'>{this.props.content.rendered}</div>
	</div> */}
			</div>
		);
	}
}

// vuejs/js/components/Education.vue
<template>
	<div class='education' itemscope itemtype='http://schema.org/CourseInstance' :class='"eduType-"+this.itemdata.course_type'>
		<div class='eduDate' itemprop='endDate' :data-actualdate='this.itemdata.completion'>{{this.itemdata.completion | formatDate('true') }}</div>
		<div class='eduEvent' itemprop='subEvent'>{{this.itemdata.title.rendered}}</div>
		<div class='eduProvider' itemprop='organizer'>
			<a :href='this.itemdata.location' target='_blank'>{{this.itemdata.provider}}</a>
			<span class='eduAward' itemprop='award' v-if='this.itemdata.award'> - {{this.itemdata.award}}</span>
		</div>
		<div class='eduDescription' v-html='this.itemdata.content.rendered' itemprop='about'></div>
	</div>
</template>

<script>
export default {
	name: 'education',
	data() {
		return {};
	},
	props: ['itemdata']
};
</script>

<style></style>
