// react/react/src/components/resume/Employer.tsx
import * as React from 'react';
import { formatDate } from 'utilities';

let presentText: string;
const getDate: IArrowFunction = (dataStr: string, present?: boolean): string => {
	return present ? presentText : formatDate(dataStr) || '';
};

export const Employer: React.StatelessComponent<IEmployerProps> = (props: IEmployerProps): JSX.Element => {
	presentText = props.presentText;
	return (
		<div className='employer' itemProp='employee' itemScope={true} itemType='http://schema.org/EmployeeRole'>
			<div className='jobDates'>
				<span className='jobStart' itemProp='startDate' data-actualdate={props.start_date}>
					{getDate(props.start_date)}
				</span>
				<span className='jobEnd' itemProp='endDate' data-actualdate={props.end_date}>
					{getDate(props.end_date, Boolean(props.still_employed))}
				</span>
			</div>
			<div className='jobPosition' itemProp='roleName'>
				{props.position}
			</div>
			<div className='jobEmployer' itemProp='name' itemScope={true} itemType='http://schema.org/Organization'>
				{props.title.rendered}
			</div>
			<div className='jobAddress' itemProp='address' itemScope={true} itemType='http://schema.org/Organization'>
				{props.location}
			</div>
			<div className='jobDescription' itemProp='description' />
			<div dangerouslySetInnerHTML={{ __html: props.content.rendered }} />
			{props.additional.length > 0 && (
				<div className='jobAddl' itemProp='alternateName'>
					{props.additionalText} {props.additional}
				</div>
			)}
		</div>
	);
};

// vuejs/js/components/Employer.vue
<template>
	<div class='employer' itemprop='employee' itemscope itemtype='http://schema.org/EmployeeRole'>
		<div class='jobDates'>
			<span class='jobStart' itemprop='startDate' :data-actualdate='this.itemdata.start_date'>
			{{this.itemdata.start_date  | formatDate}}
			</span><span class='jobEnd' itemprop='endDate' :data-actualdate='this.itemdata.end_date'>
				{{endDate}}
			</span>
		</div>
		<div class='jobPosition' itemprop='roleName'>{{this.itemdata.position}}</div>
		<div class='jobEmployer' itemprop='name' itemscope itemtype='http://schema.org/Organization'>{{this.itemdata.title.rendered}}</div>
		<div class='jobAddress' itemprop='address' itemscope itemtype='http://schema.org/Organization'>{{this.itemdata.location}}</div>
		<div class='jobDescription' itemprop='description' v-html='this.itemdata.content.rendered'></div>
		<div class='jobAddl' itemprop='alternateName' v-if='this.itemdata.additional'>ADDITIONAL: {{this.itemdata.additional}}</div>
	</div>
</template>

<script>
export default {
	name: 'employer',
	data() {
		return {};
	},
	props: ['itemdata'],
	computed: {
		endDate: function () {
			return this.itemdata.still_employed === '1' ? 'Present' :  Vue.options.filters.formatDate(this.itemdata.end_date);
		}
	}
}
</script>

<style></style>
