// react/react/src/components/resume/Resume.tsx
import * as React from 'react';
import { Education, Employer, Reference } from './';
import { TEXT_KEYS } from 'data';
interface IResumeProps extends IPageData {
	education: IEducationData[];
	work: IEmployerData[];
	references: IReferenceData[];
}
interface IResumeState {
	selectedItem: string;
}
export class Resume extends React.Component<IResumeProps, IResumeState> {
	private textKeys: ITextKeys = TEXT_KEYS;
	constructor(props: IResumeProps) {
		super(props);
		this.state = {
			selectedItem: 'resumeSummary',
		};
	}
	public handleOptionChange: IArrowFunction = (evt: IEvent): void => {
		this.setState({
			selectedItem: evt.target.id,
		});
	};
	public render(): React.ReactNode {
		return (
			<div>
				<div className='container accordionWrapper' itemScope={true} itemType='http://schema.org/ProfilePage'>
					<div id='summary'>
						<input
							checked={this.state.selectedItem === 'resumeSummary'}
							id='resumeSummary'
							name='resumeAccordion'
							onChange={this.handleOptionChange}
							type='radio'
						/>
						<label htmlFor='resumeSummary'>{this.props.title.rendered}</label>
						<article className='smallPane'>
							<p dangerouslySetInnerHTML={{ __html: this.props.content.rendered }} />
						</article>
					</div>
					<div id='employerList'>
						<input
							checked={this.state.selectedItem === 'resumework'}
							id='resumework'
							name='resumeAccordion'
							onChange={this.handleOptionChange}
							type='radio'
						/>
						<label htmlFor='resumework'>work</label>
						<article>
							{console.log('PROPS', this.props, this.props.work)}
							{this.props.work.map((employer: IEmployerData) => {
								return (
									<Employer
										key={employer.id}
										{...employer}
										presentText={this.textKeys.global.present}
										additionalText={this.textKeys.global.additional}
									/>
								);
							})}
						</article>
					</div>
					<div id='educationList'>
						<input
							id='resumeEducation'
							name='resumeAccordion'
							type='radio'
							onChange={this.handleOptionChange}
						/>
						<label htmlFor='resumeEducation'>Education / Certifications</label>
						<article>
							{this.props.education.map((cert: IEducationData) => {
								return <Education key={cert.id} {...cert} />;
							})}
						</article>
					</div>
					<div id='referenceList'>
						<input
							checked={this.state.selectedItem === 'resumeReferences'}
							id='resumeReferences'
							name='resumeAccordion'
							onChange={this.handleOptionChange}
							type='radio'
						/>
						<label htmlFor='resumeReferences'>References</label>
						<article>
							{this.props.references.map((ref: IReferenceData) => {
								return <Reference key={ref.id} {...ref} />;
							})}
						</article>
					</div>
				</div>
			</div>
		);
	}
}

// vuejs/js/views/Resume.vue
<template>
	<div class='container accordionWrapper' v-if='isLoaded' itemscope itemtype='http://schema.org/ProfilePage'>
		<div id='summary'>
			<input id='resumeSummary' name='resumeAccordion' type='radio' checked />
			<label for='resumeSummary'>{{summary[0].title.rendered}}</label>
			<article class='smallPane'>
				<p v-html='summary[0].content.rendered'></p>
			</article>
		</div>
		<div id='employerList'>
			<input id='resumeEmployers' name='resumeAccordion' type='radio' />
			<label for='resumeEmployers'>Employers</label>
			<article>
				<employer v-for='employer in employers' :key='employer.id' :itemdata=employer></employer>
			</article>
		</div>
		<div id='educationList'>
			<input id='resumeEducation' name='resumeAccordion' type='radio' />
			<label for='resumeEducation'>Education / Certifications</label>
			<article>
				<education v-for='cert in education' :key='cert.id' :itemdata=cert></education>
			</article>
		</div>
		<div id='referenceList'>
			<input id='resumeReferences' name='resumeAccordion' type='radio' />
			<label for='resumeReferences'>References</label>
			<article>
				<reference v-for='ref in references' :key='ref.id' :itemdata=ref></reference>
			</article>
		</div>
	</div>
</template>

<script>
import Employer from '../components/Employer.vue';
import Education from '../components/Education.vue';
import Reference from '../components/Reference.vue';
export default {
	name: 'Resume',
	props: [],
	data() {
		return {
			isLoaded: this.$root.pages.resume ? true : false,
			summary: this.$root.pages.resume || [],
			employers: this.$root.pages.employers || [],
			education: this.$root.pages.education || [],
			references: this.$root.pages.references || []
		};
	},
	methods: {},
	created() {
		this.$bus.$on('dataLoaded', () => {
			this.summary = this.$root.pages.resume;
			this.employers = this.$root.pages.employers;
			this.education = this.$root.pages.education;
			this.references = this.$root.pages.references;
			this.isLoaded = true;
		});
	},
	computed:{},
	components: { Employer, Education, Reference }
};
</script>

<style></style>
