// react/src/components/about/Social.tsx
import * as React from 'react';
// import { SocialItem } from './';
export interface ISocialProps extends ILoadedState {
	temp?: string;
}

export class Social extends React.Component<ISocialProps, any> {
	public render() {
		return (
			<div>
				{/* <div id='socialLinks' v-bindclassName='[showLoader ? 'hideView' : 'showView']'>
					<ul className='social-networks square spin-icon'>
					{this.props.social.map((link, index) => {
						return(
							<li key='link.id' data-dgtip='link.title.rendered'>
							<a :href='link.url' className=''icon-'+link.slug' className='icon' target='_blank' rel='noopener noreferrer'>{link.title.rendered}</a>
						</li>
						)
					})}
					</ul>
				</div> */}
			</div>
		);
	}
}

// vuejs/src/components/Social.vue
<template>
	<a class='navbar-item nestedLink' :class='"icon-menu-"+this.itemdata.slug' :href='this.itemdata.url' target='_blank'>
		{{this.itemdata.title.rendered}}
	</a>
</template>

<script>
export default {
	name: 'social',
	data() {
		return {};
	},
	props: ['itemdata']
};
</script>

<style></style>
